$schema: "https://raw.githubusercontent.com/VL-Group/modfire/main/configs/schema.json"
comments: ""
model:
  key: HashModel
  params:
    bits: 32
    backbone: resnet50
    hashMethod:
      key: STEHash
train:
  earlyStop: 100
  epoch: 10000
  valFreq: 25
  numReturns: -1
  trainer: BaseTrainer
  trainSet:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 384
      mode: Train
    pipeline:
      key: SelfSupervisedTrainingDataPipe
      params:
        nViews: 2
  querySet:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 128
      mode: Query
  database:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 128
      mode: Database
  saveDir: saved/contrastive/cifar10/32bits/
  criterion:
    key: Contrastive_D
    params:
      bits: 32
      _lambda: 1.e-4
      temperature: 0.07
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: Lamb
    params:
      lr: 1.e-3
      # for Lamb: 0.01, for others: 1e-4
      weight_decay: 0.01
  schdr:
    key: CosineAnnealingLRWarmUp
    params:
      epoch: 10000
      warmupEpoch: 50
      warmupDecay: 1.e-2
  gpu:
    gpus: 1
    vRam: -1
    wantsMore: false
