# $schema: "https://raw.githubusercontent.com/xiaosu-zhu/modfire/main/configs/schema.json"
model:
  key: HashModel
  params:
    bits: 32
    backbone: resnet50
    hashMethod: LogitHash
train:
  earlyStop: 10
  epoch: 600
  valFreq: 15
  numReturns: -1
  trainer: BaseTrainer
  trainSet:
    key: CIFAR10
    params:
      root: data/cifar10/
      batchSize: 128
  querySet:
    key: CIFAR10
    params:
      root: data/cifar10/
      batchSize: 128
  database:
    key: CIFAR10
    params:
      root: data/cifar10/
      batchSize: 128
  saveDir: saved/csq/cifar10/32bits/
  criterion:
    key: CSQ
    params:
      bits: 32
      numClasses: 10
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: Lamb
    params:
      lr: 1.e-3
      # for Lamb: 0.01, for others: 1e-4
      weight_decay: 0.01
  schdr:
    key: CosineAnnealingLR
    params:
      T_max: 100
  gpu:
    gpus: 1
    vRam: -1
    wantsMore: false
