$schema: "https://raw.githubusercontent.com/VL-Group/modfire/main/configs/schema.json"
summary: 32bits_ProductQuantization_PQNet_resnet50_cifar10
model:
  key: PQModel
  params:
    # 32 bits
    m: 4
    k: 256
    d: 256
    intraNormalization: false
    backbone: resnet50
    pqMethod: SoftPQ
train:
  earlyStop: 100
  epoch: 10000
  valFreq: 25
  numReturns: -1
  trainer: BaseTrainer
  trainSet:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 384
      mode: Train
    pipeline:
      key: SelfSupervisedTrainingDataPipe
      params:
        nViews: 2
  querySet:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 128
      mode: Query
  database:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 128
      mode: Database
  saveDir: saved/spq/easy/cifar10/32bits/
  criterion:
    key: SPQ
    params:
      d: 256
      temperature: 0.1 # 1/10
      tContrastive: 0.5
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: Lamb
    params:
      lr: 1.e-3
      # for Lamb: 0.01, for others: 1e-4
      weight_decay: 0.01
  schdr:
    key: CosineAnnealingLR
    params:
      T_max: 500
  gpu:
    gpus: 1
    vRam: -1
    wantsMore: false
