$schema: "https://raw.githubusercontent.com/VL-Group/modfire/main/configs/schema.json"
comments: ""
model:
  key: HashModel
  params:
    bits: 32
    backbone: resnet50
    hashMethod:
      key: LogitHash
      # params:
      #   temperature:
      #     key: Constant
      #     params:
      #       initValue: 1.0
train:
  earlyStop: 10
  epoch: 100
  valFreq: 5
  numReturns: -1
  trainer: BaseTrainer
  trainSet:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 128
      mode: Train
  querySet:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 128
      mode: Query
  database:
    key: CIFAR10
    params:
      root: data/easy/cifar10/
      batchSize: 128
      mode: Database
  saveDir: saved/csq_d/cifar10/32bits/
  criterion:
    key: CSQ_D
    params:
      bits: 32
      numClasses: 10
      addRegularization: true
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: Lamb
    params:
      lr: 1.e-3
      # for Lamb: 0.01, for others: 1e-4
      weight_decay: 0.01
  schdr:
    key: CosineAnnealingLRWarmUp
    params:
      epoch: 100
      warmupEpoch: 5
      warmupDecay: 1.e-2
  gpu:
    gpus: 1
    vRam: 15000
    wantsMore: false
